title: Produktseite

tabs:
  teaser:
    label: Produktübersicht
    sections:
      info:
        label: Info
        type: info
        text: |
          Die Informationen in diesem Tab werden auf der Seite "Produkte" genutzt um die Liste von Produkten zusammenzustellen.
      teaserContent:
        type: fields
        fields:
          hero:
            label: Hero Bild
            type: files
            uploads: image
            min: 1
            max: 1
            layout: cards
          autor:
            label: Autoren-Zeile (optional)
            type: text
            help: Dieser Text wird ohne Zeilenschub unter der Überschrift angezeigt.
          summary:
            label: Zusammenfassung / Teaser
            type: textarea
            buttons: true
            size: small
            help: Dieser Text wird in der Produktübersicht angezeigt.
  content:
    label: Produktdetails
    columns:
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
              blocks:
                label: Inhalt
                type: blocks
      sidebar:
        width: 1/3
        sections:
          files:
            label: Alle Dateien
            type: files
