title: Produkt Seite

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          blocks:
            label: Inhalt
            type: blocks
  sidebar:
    width: 1/3
    sections:
      files:
        label: Dateien
        type: files
