title: Produktübersicht

options:
  changeTemplate:
    - default
    - videos

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          blocks:
            label: Inhalt
            type: blocks
      pages:
        label: Produktseiten
        type: pages
        template: product
  sidebar:
    width: 1/3
    sections:
      files:
        label: Dateien
        type: files
