title: Site

columns:
  - width: 1/2
    sections:
      welcome:
        label: Hallo Babs und Christof!
        type: info
        theme: info
        text: |
          Ihr findet über das Kirby-Panel verteilt diese Hilfstexte. Ich habe sie überall dort geschrieben, wo ich glaube, dass ein paar Infos hilfreich sein könnten. Die Texte sind manchmal farbig hinterlegt, so wie dieser, und manchmal sind sie in grau unterhalb von Elementen.

          Hilfe? (link: tel:00491748940954 text: Hier klicken um mich anzurufen!)

          Liebe Grüße,
          Wenzel
      seiten:
        type: pages
  - width: 1/2
    sections:
      informationen:
        type: fields
        fields:
          description:
            label: "Beschreibung für Suchmaschinen"
            help: "Google zeigt bis zu 160 Zeichen in den Suchergebnissen an"
            type: textarea
            size: small
            required: true
            spellcheck: true
            buttons: false
            counter: true
          infoOGImage:
            type: info
            label: Open Graph Info
            theme: info
            text: |
              OpenGraph ist ein Standard für elegantere Vorschauen von Links. Open Graph Bilder werden von Diensten wie iMessage, Facebook, etc. angezeigt. Sie sind das Vorschaubild, das erscheint, wenn dort ein Link geteilt wird. Ich habe in diese Webseite Open Graph Unterstützung eingebaut.

              Open Graph Bilder dürfen jedes Seitenverhältnis nutzen, am besten sind jedoch quadratische Grafiken. Die Dateigröße darf nicht mehr als 1MB sein und nicht kleiner als 120x120 PX. Am besten 1024x1024 PX oder größer.

              Bilder sollten keine zusätzlichen Informationen beinhalten, sie dienen ausschließlich der Illustration und werden von Screen-Readern nicht beschrieben.
          ogImage:
            label: "Standard Open Graph Bild"
            help: |
              Dieses Bild wird als „Open Graph”-Bild für alle Seiten genutzt, die kein eigenes Bild festlegen. (link: https://ogp.me text: Mehr Informationen zu Open Graph. target: _blank)
            type: files
            max: 1
            layout: cards
            image:
              cover: true
              ratio: 1/1
