title: Site

columns:
  - width: 2/3
    sections:
      seiten:
        type: pages
  - width: 1/3
    sections:
      informationen:
        type: fields
        fields:
          description:
            label: "Beschreibung für Suchmaschinen"
            type: textarea
            size: small
            required: true
            spellcheck: true
            buttons: false
            help: "Google zeigt bis zu 160 Zeichen in den Suchergebnissen an"
            counter: true
